name: PHP 7.* Tests

on:
  push:    # Trigger on code pushes
    branches:
      - master
  pull_request:  # Trigger on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4] # Define the PHP versions to test

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, curl 
          coverage: none # Skip code coverage tools for faster testing

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: composer install --no-progress --no-suggest

      # Step 4: Run Tests
      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
